steps:
  - uses: actions/checkout@v4
  - uses: FirebaseExtended/action-hosting-deploy@v0
    with:
      repoToken: '${{ secrets.GITHUB_TOKEN }}'
      firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
      projectId: 'fir-result-eeca5'
      channelId: 'live'
      entryPoint: '.'
